#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@zerotier[-1]
	commit ucitrack

	delete firewall.zerotier
	commit firewall
EOF

/etc/init.d/luci-zerotier enable

rm -f /tmp/luci-indexcache
exit 0